// Topic pool for Sal Negra Tenerife blog.
// Every entry targets real Google search intent in es-ES and en-GB.
// Add new topics at the bottom — id must stay unique.

module.exports = [
  {
    id: 1,
    slug_es: 'mejores-restaurantes-mariscos-costa-adeje',
    slug_en: 'best-seafood-restaurants-costa-adeje',
    category_es: 'Guía',
    category_en: 'Guide',
    title_es: 'Mejores restaurantes de mariscos en Costa Adeje: la guía local',
    title_en: 'Best seafood restaurants in Costa Adeje: a local guide',
    keywords_es: ['restaurantes mariscos Costa Adeje', 'marisco fresco Tenerife sur', 'dónde comer marisco Costa Adeje'],
    keywords_en: ['seafood restaurants Costa Adeje', 'fresh seafood south Tenerife', 'where to eat seafood Costa Adeje'],
    angle: 'Lista curada con criterios reales (estacionalidad, origen del producto, personal cualificado). Sal Negra mencionado como una opción, no la única.',
    image: 'gallery2.jpg'
  },
  {
    id: 2,
    slug_es: 'mojo-verde-canario-historia-receta',
    slug_en: 'canary-mojo-verde-history-recipe',
    category_es: 'Tradición',
    category_en: 'Tradition',
    title_es: 'Mojo verde canario: historia, receta y con qué platos maridarlo',
    title_en: 'Canary mojo verde: history, recipe and what to pair it with',
    keywords_es: ['mojo verde canario', 'receta mojo verde', 'salsas canarias'],
    keywords_en: ['canary mojo verde', 'green mojo recipe', 'canary sauces'],
    angle: 'Historia, variantes regionales, receta y maridajes. Posicionar en búsquedas sobre gastronomía canaria.',
    image: 'gallery4.jpg'
  },
  {
    id: 3,
    slug_es: 'papas-arrugadas-mojo-origen',
    slug_en: 'papas-arrugadas-canary-origin',
    category_es: 'Tradición',
    category_en: 'Tradition',
    title_es: 'Papas arrugadas con mojo: el plato más canario explicado',
    title_en: 'Papas arrugadas with mojo: the most Canary dish explained',
    keywords_es: ['papas arrugadas', 'papas arrugadas mojo', 'gastronomía canaria'],
    keywords_en: ['papas arrugadas', 'wrinkled potatoes canary', 'canary cuisine'],
    angle: 'Origen, variedades de papa antigua canaria, técnica correcta de cocción, acompañamientos.',
    image: 'gallery5.jpg'
  },
  {
    id: 4,
    slug_es: 'vinos-canarios-tenerife-guia-maridaje',
    slug_en: 'canary-wines-tenerife-pairing-guide',
    category_es: 'Vinos',
    category_en: 'Wine',
    title_es: 'Vinos canarios de Tenerife: guía de maridaje para turistas',
    title_en: 'Canary wines of Tenerife: a pairing guide for visitors',
    keywords_es: ['vinos canarios', 'vinos Tenerife', 'DO Tacoronte', 'Listán Blanco'],
    keywords_en: ['canary wines', 'tenerife wine', 'listan blanco', 'canary wine pairing'],
    angle: 'Introducción accesible a las DO de Tenerife, uvas autóctonas, maridajes concretos con platos del restaurante.',
    image: 'gallery6.jpg'
  },
  {
    id: 5,
    slug_es: 'que-comer-tenerife-primera-vez',
    slug_en: 'what-to-eat-tenerife-first-time',
    category_es: 'Guía',
    category_en: 'Guide',
    title_es: 'Qué comer en Tenerife por primera vez: 10 platos imprescindibles',
    title_en: 'What to eat in Tenerife first time: 10 must-try dishes',
    keywords_es: ['qué comer en Tenerife', 'platos típicos Tenerife', 'gastronomía Tenerife'],
    keywords_en: ['what to eat in Tenerife', 'typical tenerife dishes', 'tenerife food guide'],
    angle: 'Top 10 platos tradicionales con explicación breve y dónde encontrarlos en Costa Adeje/Los Cristianos.',
    image: 'gallery7.jpg'
  },
  {
    id: 6,
    slug_es: 'pulpo-canario-como-pedirlo',
    slug_en: 'canary-octopus-how-to-order',
    category_es: 'Producto',
    category_en: 'Product',
    title_es: 'Pulpo canario: de dónde viene y cómo pedirlo en un restaurante',
    title_en: 'Canary octopus: where it comes from and how to order it',
    keywords_es: ['pulpo canario', 'pulpo Tenerife', 'cómo cocinar pulpo'],
    keywords_en: ['canary octopus', 'octopus tenerife', 'how to order octopus'],
    angle: 'Origen (pesca artesanal), diferencias frente a pulpo gallego, técnicas de cocción, señales de calidad en carta.',
    image: 'gallery8.jpg'
  },
  {
    id: 7,
    slug_es: 'cena-empresa-tenerife-sur',
    slug_en: 'corporate-dinner-south-tenerife',
    category_es: 'Eventos',
    category_en: 'Events',
    title_es: 'Cena de empresa en Tenerife sur: cómo organizarla sin errores',
    title_en: 'Corporate dinner in south Tenerife: how to get it right',
    keywords_es: ['cena empresa Tenerife', 'eventos empresa Costa Adeje', 'menú grupo Tenerife'],
    keywords_en: ['corporate dinner tenerife', 'company events costa adeje', 'group menu tenerife'],
    angle: 'Checklist práctico: aforo, menú cerrado, dietas especiales, timing, presupuesto. CTA a menús especiales de Sal Negra.',
    image: 'evento-sax-1.jpg'
  },
  {
    id: 8,
    slug_es: 'los-cristianos-donde-comer-local',
    slug_en: 'los-cristianos-local-food-spots',
    category_es: 'Zona',
    category_en: 'Area',
    title_es: 'Los Cristianos: dónde comer como un local lejos de las trampas turísticas',
    title_en: 'Los Cristianos: where to eat like a local away from tourist traps',
    keywords_es: ['dónde comer Los Cristianos', 'restaurantes Los Cristianos', 'comer bien Los Cristianos'],
    keywords_en: ['where to eat los cristianos', 'local restaurants los cristianos', 'eat like a local tenerife'],
    angle: 'Consejos para distinguir restaurantes locales honestos. 5 señales concretas. Sin lista de sitios específicos.',
    image: 'gallery3.jpg'
  },
  {
    id: 9,
    slug_es: 'atun-rojo-canarias-temporada',
    slug_en: 'canary-bluefin-tuna-season',
    category_es: 'Producto',
    category_en: 'Product',
    title_es: 'Atún rojo de Canarias: temporada, corte y cómo saborearlo',
    title_en: 'Canary bluefin tuna: season, cuts and how to enjoy it',
    keywords_es: ['atún rojo Canarias', 'atún Tenerife', 'ronqueo atún'],
    keywords_en: ['canary bluefin tuna', 'tuna tenerife', 'bluefin ronqueo'],
    angle: 'Temporada (primavera-verano), cortes nobles, técnicas culinarias, sostenibilidad de la pesca en Canarias.',
    image: 'gallery1.jpg'
  },
  {
    id: 10,
    slug_es: 'paella-verdadera-ingredientes-trampas',
    slug_en: 'real-paella-ingredients-red-flags',
    category_es: 'Gastronomía',
    category_en: 'Food',
    title_es: 'Paella de verdad en Tenerife: ingredientes reales y trampas a evitar',
    title_en: 'Real paella in Tenerife: real ingredients and red flags',
    keywords_es: ['paella Tenerife', 'paella auténtica Costa Adeje', 'buena paella turistas'],
    keywords_en: ['paella tenerife', 'authentic paella costa adeje', 'real paella tourists'],
    angle: 'Señales de paella real vs. industrial. Variedades (valenciana, marisco, mixta). Temperatura y tiempo correctos.',
    image: 'gallery2.jpg'
  },
  {
    id: 11,
    slug_es: 'cumpleanos-restaurante-vistas-mar-tenerife',
    slug_en: 'birthday-sea-view-restaurant-tenerife',
    category_es: 'Eventos',
    category_en: 'Events',
    title_es: 'Cumpleaños en un restaurante con vistas al mar en Tenerife: ideas',
    title_en: 'Birthday at a sea-view restaurant in Tenerife: ideas',
    keywords_es: ['cumpleaños restaurante Tenerife', 'restaurante vistas mar Tenerife', 'celebrar cumpleaños Costa Adeje'],
    keywords_en: ['birthday restaurant tenerife', 'sea view restaurant tenerife', 'celebrate birthday costa adeje'],
    angle: 'Organización, detalles sorpresa, elección de menú, reserva anticipada. CTA reservas.',
    image: 'gallery7.jpg'
  },
  {
    id: 12,
    slug_es: 'queso-canario-denominaciones-maridaje',
    slug_en: 'canary-cheese-denominations-pairing',
    category_es: 'Producto',
    category_en: 'Product',
    title_es: 'Quesos canarios: denominaciones de origen y maridajes',
    title_en: 'Canary cheeses: designations of origin and pairings',
    keywords_es: ['quesos canarios', 'queso palmero', 'queso majorero', 'queso flor de Guía'],
    keywords_en: ['canary cheese', 'palmero cheese', 'majorero cheese', 'flor de guia cheese'],
    angle: 'Las 3 DOP canarias (Palmero, Majorero, Flor de Guía). Características, maridajes con vinos canarios.',
    image: 'gallery4.jpg'
  },
  {
    id: 13,
    slug_es: 'verano-tenerife-platos-frescos',
    slug_en: 'summer-tenerife-fresh-dishes',
    category_es: 'Temporada',
    category_en: 'Season',
    title_es: 'Verano en Tenerife: 7 platos frescos para los días calurosos',
    title_en: 'Summer in Tenerife: 7 fresh dishes for hot days',
    keywords_es: ['comer verano Tenerife', 'platos frescos verano', 'gazpacho canario'],
    keywords_en: ['summer food tenerife', 'fresh summer dishes', 'cold dishes tenerife'],
    angle: 'Ensaladas, gazpachos, pescado a la plancha ligero, ceviches locales. Sin estaciones de frío.',
    image: 'gallery5.jpg'
  },
  {
    id: 14,
    slug_es: 'maridaje-mariscos-vino-canario',
    slug_en: 'seafood-canary-wine-pairing',
    category_es: 'Vinos',
    category_en: 'Wine',
    title_es: 'Maridaje mariscos con vino canario: la guía rápida',
    title_en: 'Seafood and canary wine pairing: the quick guide',
    keywords_es: ['maridaje mariscos vino', 'qué vino con marisco', 'vino canario marisco'],
    keywords_en: ['seafood wine pairing', 'what wine with seafood', 'canary wine seafood'],
    angle: 'Tabla de maridajes rápida: gamba + Listán Blanco, pulpo + Malvasía seca, etc.',
    image: 'gallery6.jpg'
  },
  {
    id: 15,
    slug_es: 'ropa-vieja-canaria-receta',
    slug_en: 'canary-ropa-vieja-recipe',
    category_es: 'Tradición',
    category_en: 'Tradition',
    title_es: 'Ropa vieja canaria: qué es y por qué no es el plato cubano',
    title_en: 'Canary ropa vieja: what it is and why it differs from the Cuban dish',
    keywords_es: ['ropa vieja canaria', 'receta ropa vieja', 'plato tradicional canario'],
    keywords_en: ['canary ropa vieja', 'ropa vieja recipe', 'traditional canary dish'],
    angle: 'Origen, diferencias con versión cubana, receta tradicional, cuándo y dónde probarlo.',
    image: 'gallery8.jpg'
  },
  {
    id: 16,
    slug_es: 'cigalas-gambas-langostinos-diferencias',
    slug_en: 'langoustine-prawn-shrimp-differences',
    category_es: 'Producto',
    category_en: 'Product',
    title_es: 'Cigalas, gambas y langostinos: aprender las diferencias antes de pedir',
    title_en: 'Langoustine, prawn and shrimp: learn the differences before ordering',
    keywords_es: ['diferencia cigala gamba langostino', 'marisco tipos', 'cómo pedir marisco'],
    keywords_en: ['langoustine vs prawn vs shrimp', 'seafood types', 'how to order shellfish'],
    angle: 'Diferencias morfológicas y de sabor. Tabla comparativa. Cómo identificarlos en carta.',
    image: 'gallery1.jpg'
  },
  {
    id: 17,
    slug_es: 'gofio-canario-que-es',
    slug_en: 'canary-gofio-what-is-it',
    category_es: 'Tradición',
    category_en: 'Tradition',
    title_es: 'Gofio canario: qué es, cómo se usa y por qué deberías probarlo',
    title_en: 'Canary gofio: what it is, how to use it and why you should try it',
    keywords_es: ['gofio canario', 'qué es el gofio', 'recetas gofio'],
    keywords_en: ['canary gofio', 'what is gofio', 'gofio recipes'],
    angle: 'Historia prehispánica, variantes (trigo, millo, mezcla), recetas modernas, valor nutricional.',
    image: 'gallery3.jpg'
  },
  {
    id: 18,
    slug_es: 'navidad-tenerife-menus-especiales',
    slug_en: 'christmas-tenerife-special-menus',
    category_es: 'Eventos',
    category_en: 'Events',
    title_es: 'Navidad en Tenerife: cómo elegir menú de empresa y familiar',
    title_en: 'Christmas in Tenerife: choosing corporate and family menus',
    keywords_es: ['navidad Tenerife restaurante', 'menú navidad Costa Adeje', 'cena empresa navidad'],
    keywords_en: ['christmas tenerife restaurant', 'christmas menu costa adeje', 'company christmas dinner'],
    angle: 'Checklist de reserva navideña, menús cerrados vs. a la carta, noche buena vs. noche vieja.',
    image: 'menu-nochevieja-cover.jpg'
  },
  {
    id: 19,
    slug_es: 'productos-km0-tenerife-restaurantes',
    slug_en: 'local-produce-tenerife-restaurants',
    category_es: 'Producto',
    category_en: 'Product',
    title_es: 'Producto km 0 en Tenerife: por qué un buen restaurante lo prioriza',
    title_en: 'Local produce in Tenerife: why good restaurants prioritise it',
    keywords_es: ['km 0 Tenerife', 'producto local Canarias', 'restaurante producto local'],
    keywords_en: ['km 0 tenerife', 'local produce canary', 'farm to table tenerife'],
    angle: 'Filosofía, cadena de proveedores corta, ejemplos concretos (tomate, papa, vino, pescado).',
    image: 'gallery4.jpg'
  },
  {
    id: 20,
    slug_es: 'puesta-sol-tenerife-mejores-sitios-cenar',
    slug_en: 'tenerife-sunset-best-dinner-spots',
    category_es: 'Zona',
    category_en: 'Area',
    title_es: 'Puesta de sol en Tenerife: los mejores sitios para cenar frente al mar',
    title_en: 'Tenerife sunset: the best spots to dine by the sea',
    keywords_es: ['puesta sol Tenerife cenar', 'restaurante atardecer Costa Adeje', 'cenar vista mar Tenerife'],
    keywords_en: ['tenerife sunset dinner', 'costa adeje sunset restaurant', 'sea view dinner tenerife'],
    angle: 'Horarios según estación, qué zonas (Costa Adeje, La Caleta, Los Cristianos), qué pedir para aprovechar la vista.',
    image: 'gallery2.jpg'
  },
  {
    id: 21,
    slug_es: 'tapas-tenerife-cultura-platos',
    slug_en: 'tenerife-tapas-culture-dishes',
    category_es: 'Tradición',
    category_en: 'Tradition',
    title_es: 'Tapas en Tenerife: cultura, platos y cómo disfrutar una ruta',
    title_en: 'Tapas in Tenerife: culture, dishes and how to enjoy a tapas trail',
    keywords_es: ['tapas Tenerife', 'ruta tapas Costa Adeje', 'tapas canarias típicas'],
    keywords_en: ['tenerife tapas', 'tapas trail costa adeje', 'typical canary tapas'],
    angle: 'Origen, diferencias con tapas peninsulares, top tapas canarias, cómo montar una ruta.',
    image: 'gallery5.jpg'
  },
  {
    id: 22,
    slug_es: 'plancha-brasa-diferencias-pescado',
    slug_en: 'griddle-vs-grill-fish-differences',
    category_es: 'Gastronomía',
    category_en: 'Food',
    title_es: 'Plancha o brasa: qué técnica pedir según el pescado',
    title_en: 'Griddle vs grill: which technique to order for each fish',
    keywords_es: ['plancha brasa pescado', 'cocinar pescado a la plancha', 'técnicas pescado restaurante'],
    keywords_en: ['griddle vs grill fish', 'cooking fish tenerife', 'fish restaurant techniques'],
    angle: 'Diferencias técnicas, qué pescado va mejor con cada una. Consejos para pedir.',
    image: 'gallery7.jpg'
  },
  {
    id: 23,
    slug_es: 'mero-canario-como-cocinarlo',
    slug_en: 'canary-grouper-how-to-cook',
    category_es: 'Producto',
    category_en: 'Product',
    title_es: 'Mero canario: el rey silencioso de la carta del sur',
    title_en: 'Canary grouper: the quiet king of southern Tenerife menus',
    keywords_es: ['mero canario', 'mero Tenerife', 'pescado blanco canario'],
    keywords_en: ['canary grouper', 'grouper tenerife', 'canary white fish'],
    angle: 'Características del mero, cómo se cocina, por qué es caro, temporada óptima.',
    image: 'gallery6.jpg'
  },
  {
    id: 24,
    slug_es: 'comer-sin-gluten-tenerife-sur',
    slug_en: 'gluten-free-south-tenerife',
    category_es: 'Guía',
    category_en: 'Guide',
    title_es: 'Comer sin gluten en el sur de Tenerife: lo que debes saber',
    title_en: 'Eating gluten-free in south Tenerife: what to know',
    keywords_es: ['sin gluten Tenerife', 'celíaco Costa Adeje', 'restaurantes sin gluten Tenerife'],
    keywords_en: ['gluten free tenerife', 'celiac costa adeje', 'gluten free restaurants south tenerife'],
    angle: 'Platos canarios naturalmente sin gluten, cómo preguntar, señales de seguridad en un restaurante.',
    image: 'gallery8.jpg'
  },
  {
    id: 25,
    slug_es: 'vieiras-navajas-tenerife-cuando-pedirlas',
    slug_en: 'scallops-razor-clams-tenerife-when',
    category_es: 'Producto',
    category_en: 'Product',
    title_es: 'Vieiras y navajas en Tenerife: cuándo pedirlas para no equivocarte',
    title_en: 'Scallops and razor clams in Tenerife: when to order them',
    keywords_es: ['vieiras Tenerife', 'navajas Canarias', 'marisco delicado'],
    keywords_en: ['scallops tenerife', 'razor clams canary', 'delicate shellfish'],
    angle: 'Temporada óptima, señales de frescura, técnicas culinarias, precio justo.',
    image: 'gallery1.jpg'
  },
  {
    id: 26,
    slug_es: 'aniversario-pareja-tenerife-cena-romantica',
    slug_en: 'anniversary-tenerife-romantic-dinner',
    category_es: 'Eventos',
    category_en: 'Events',
    title_es: 'Aniversario en Tenerife: cómo planificar una cena romántica sin clichés',
    title_en: 'Anniversary in Tenerife: planning a romantic dinner without clichés',
    keywords_es: ['cena romántica Tenerife', 'aniversario Costa Adeje', 'restaurante romántico vistas mar'],
    keywords_en: ['romantic dinner tenerife', 'anniversary costa adeje', 'romantic sea view restaurant'],
    angle: 'Detalles finos: mesa, iluminación, menú degustación, sorpresas sin kitsch.',
    image: 'gallery3.jpg'
  },
  {
    id: 27,
    slug_es: 'sardinas-caballa-azul-tenerife',
    slug_en: 'sardines-mackerel-tenerife',
    category_es: 'Producto',
    category_en: 'Product',
    title_es: 'Pescado azul en Tenerife: sardinas, caballa y por qué son subestimados',
    title_en: 'Blue fish in Tenerife: sardines, mackerel and why they are underrated',
    keywords_es: ['pescado azul Tenerife', 'sardinas Canarias', 'caballa receta'],
    keywords_en: ['blue fish tenerife', 'canary sardines', 'mackerel recipe'],
    angle: 'Valor nutricional, técnicas clásicas (plancha, escabeche), por qué subvalorados.',
    image: 'gallery4.jpg'
  },
  {
    id: 28,
    slug_es: 'frituras-pescado-canario',
    slug_en: 'canary-fried-seafood',
    category_es: 'Gastronomía',
    category_en: 'Food',
    title_es: 'Fritura canaria: chicharros, cazones y el arte del rebozado justo',
    title_en: 'Canary fried seafood: chicharros, cazones and the craft of the right batter',
    keywords_es: ['fritura pescado Tenerife', 'chicharrones pescado', 'rebozado canario'],
    keywords_en: ['canary fried fish', 'fried seafood tenerife', 'canary batter fish'],
    angle: 'Técnica (temperatura aceite, tipo de harina), pescados ideales, errores comunes.',
    image: 'gallery5.jpg'
  },
  {
    id: 29,
    slug_es: 'menu-degustacion-tenerife-cuando-pedir',
    slug_en: 'tasting-menu-tenerife-when-to-order',
    category_es: 'Guía',
    category_en: 'Guide',
    title_es: 'Menú degustación en Tenerife: cuándo tiene sentido pedirlo',
    title_en: 'Tasting menu in Tenerife: when it makes sense to order one',
    keywords_es: ['menú degustación Tenerife', 'menú degustación Costa Adeje', 'cuando pedir degustación'],
    keywords_en: ['tasting menu tenerife', 'degustation menu costa adeje', 'when to order tasting menu'],
    angle: 'Ventajas, desventajas, presupuesto realista, momentos ideales (aniversario, primera vez).',
    image: 'gallery7.jpg'
  },
  {
    id: 30,
    slug_es: 'sostenibilidad-pesca-canarias',
    slug_en: 'sustainable-fishing-canary-islands',
    category_es: 'Producto',
    category_en: 'Product',
    title_es: 'Pesca sostenible en Canarias: cómo saber si tu pescado es responsable',
    title_en: 'Sustainable fishing in the Canary Islands: how to know your fish is responsible',
    keywords_es: ['pesca sostenible Canarias', 'pescado sostenible Tenerife', 'consumo responsable pescado'],
    keywords_en: ['sustainable fishing canary islands', 'sustainable seafood tenerife', 'responsible fish consumption'],
    angle: 'Sellos, temporadas de veda, especies sobrepescadas, alternativas locales.',
    image: 'gallery2.jpg'
  }
];
